### ISSUE TITLE
Some users are not mapped

### ISSUE THREAD

**Issue by HassanAkbar** [ietf-ribose/svn-github-convert#59]
In the following repos `tsvwg`, `emailcore`, and `dmarc` some users are not mapped, Here is the list of all user for these 3 repos.

## DMARC
```yaml
superuser@gmail.com:
  email: superuser@gmail.com
  name:
  username:

kboth+ietf@drkurt.com:
  email: kboth+ietf@drkurt.com
  name:
  username:

seth@sethblank.com:
  email: seth@sethblank.com
  name:
  username:

scott@kitterman.com:
  email: scott@kitterman.com
  name:
  username:

dcrocker@bbiw.net:
  email: dcrocker@bbiw.net
  name:
  username:

todd.herr@valimail.com:
  email: todd.herr@valimail.com
  name:
  username:

fosterd@bayviewphysicians.com:
  email: fosterd@bayviewphysicians.com
  name:
  username:

alexey.melnikov@isode.com:
  email: alexey.melnikov@isode.com
  name:
  username:

mike@mtcc.com:
  email: mike@mtcc.com
  name:
  username:

dougfoster.emailstandards@gmail.com:
  email: dougfoster.emailstandards@gmail.com
  name:
  username:

mail@wander.science:
  email: mail@wander.science
  name:
  username:

dpa-ietf@aegee.org:
  email: dpa-ietf@aegee.org
  name:
  username:

alex_brotman@comcast.com:
  email: alex_brotman@comcast.com
  name:
  username:

draft-ietf-dmarc-arc-protocol@ietf.org:
  email: draft-ietf-dmarc-arc-protocol@ietf.org
  name:
  username:

draft-ietf-dmarc-rfc7601bis@ietf.org:
  email: draft-ietf-dmarc-rfc7601bis@ietf.org
  name:
  username:

draft-ietf-dmarc-interoperability@ietf.org:
  email: draft-ietf-dmarc-interoperability@ietf.org
  name:
  username:

draft-ietf-dmarc-arc-multi@ietf.org:
  email: draft-ietf-dmarc-arc-multi@ietf.org
  name:
  username:

draft-ietf-dmarc-psd@ietf.org:
  email: draft-ietf-dmarc-psd@ietf.org
  name:
  username:

freddie@leemankuiper.nl:
  email: freddie@leemankuiper.nl
  name:
  username:

smj@crash.com:
  email: smj@crash.com
  name:
  username:
```

## Emailcore
```yaml
alexey.melnikov@isode.com:
  email: alexey.melnikov@isode.com
  name:
  username:

julien@trigofacile.com:
  email: julien@trigofacile.com
  name:
  username:

todd.herr@valimail.com:
  email: todd.herr@valimail.com
  name:
  username:

resnick@episteme.net:
  email: resnick@episteme.net
  name:
  username:
```

## tsvwg
```yaml
gorry@erg.abdn.ac.uk:
  email: gorry@erg.abdn.ac.uk
  name:
  username: 
wes@mti-systems.com:
  email: wes@mti-systems.com
  name:
  username: 
moeller0@gmx.de:
  email: moeller0@gmx.de
  name:
  username: 
pete@heistp.net:
  email: pete@heistp.net
  name:
  username: 
jmpolk@cisco.com:
  email: jmpolk@cisco.com
  name:
  username: 
draft-ietf-tsvwg-source-quench@tools.ietf.org:
  email: draft-ietf-tsvwgsource-quench@tools.ietf.org
  name:
  username:
draft-ietf-tsvwg-l4s-arch@ietf.org:
  email: draft-ietf-tsvwg-l4s-arch@ietf.org
  name:
  username:
draft-ietf-tsvwg-aqm-dualq-coupled@ietf.org:
  email: draft-ietf-tsvwg-aqm-dualq-coupled@ietf.org
  name:
  username:
david.black@emc.com:
  email: david.black@emc.com
  name:
  username:
chromatix99@gmail.com:
  email: chromatix99@gmail.com
  name:
  username:
ietf@bobbriscoe.net:
  email: ietf@bobbriscoe.net
  name:
  username:
jholland@akamai.com:
  email: jholland@akamai.com
  name:
  username:
g.white@cablelabs.com:
  email: g.white@cablelabs.com
  name:
  username:
```

**Comment by HassanAkbar** [comment]
@ronaldtse @rjsparks We still have some missing Github usernames in other repositories.

**Comment by HassanAkbar** [comment]
I was able to find these users from the previous list and GitHub search.

## DMARC
```yaml
tim@eudaemon.net:
  email: tim@eudaemon.net
  name: Tim Draegen
  username: tdraegen

vesely@tana.it:
  email: vesely@tana.it
  name: Alessandro Vesely
  username: alevesely

tjw.ietf@gmail.com:
  email: tjw.ietf@gmail.com
  name: Tim Wicinski
  username: moonshiner

johnl@taugh.com:
  email: johnl@taugh.com
  name: John R. Levine
  username: jrlevine

fenton@bluepopcorn.net:
  email: fenton@bluepopcorn.net
  name: Jim Fenton
  username: jimfenton

johnl@taugh.com:
  email: johnl@taugh.com
  name: John R. Levine
  username: jrlevine

Todd Herr:
  email: toddmherr@gmail.com
  name: Todd Herr
  username: toddherr
```

## Emailcore
```yaml
vesely@tana.it:
  email: vesely@tana.it
  name: Alessandro Vesely
  username: alevesely

ned.freed@mrochek.com:
  email: ned.freed@mrochek.com
  name: Ned Freed
  username: NedFreed
```

## tsvwg
```yaml
lars.eggert@nokia.com:
  email: lars@eggert.org
  name: Lars Eggert
  username: larseggert

magnus.westerlund@ericsson.com:
  email: magnus.westerlund@ericsson.com
  name: Magnus Westerlund
  username: gloinul
```

**Comment by rjsparks** [comment]
do not map anything that looks like draft-*@ietf.org (or draft-*@tools.ietf.org)

**Comment by rjsparks** [comment]
I will ask the wg chairs for help with the remaining unmapped users

**Comment by HassanAkbar** [comment]
Thanks @rjsparks

**Comment by toddherr** [comment]
Some more for DMARC:

superuser@gmail.com:
  email: superuser@gmail.com
  name: Murray Kucherawy
  username: mskucherawy

kboth+ietf@drkurt.com:
  email: kboth+ietf@drkurt.com
  name: Kurt Andersen
  username: kurta

seth@sethblank.com:
  email: seth@sethblank.com
  name: Seth Blank
  username: AntiFreeze

scott@kitterman.com:
  email: scott@kitterman.com
  name: Scott Kitterman
  username: kitterma

dcrocker@bbiw.net:
  email: dcrocker@bbiw.net
  name: Dave Crocker
  username: davecrocker

todd.herr@valimail.com:
  email: todd.herr@valimail.com
  name: Todd Herr
  username: toddherr

fosterd@bayviewphysicians.com:
  email: fosterd@bayviewphysicians.com
  name: Doug Foster
  username:

alexey.melnikov@isode.com:
  email: alexey.melnikov@isode.com
  name: Alexey Melnikov
  username:

mike@mtcc.com:
  email: mike@mtcc.com
  name: Michael Thomas
  username:

dougfoster.emailstandards@gmail.com:
  email: dougfoster.emailstandards@gmail.com
  name: Doug Foster (same as fosterd@bayviewphysicians.com)
  username:

mail@wander.science:
  email: mail@wander.science
  name: Matthaus Wander
  username: mwander

alex_brotman@comcast.com:
  email: alex_brotman@comcast.com
  name: Alex Brotman
  username: abrotman

smj@crash.com:
  email: smj@crash.com
  name: Steve Jones
  username: smjones

**Comment by ronaldtse** [comment]
Latest updates. Only a few we can't find GitHub usernames for.

## DMARC
```yaml
superuser@gmail.com:
  email: superuser@gmail.com
  name: Murray Kucherawy
  username: mskucherawy

kboth+ietf@drkurt.com:
  email: kboth+ietf@drkurt.com
  name: Kurt Andersen
  username: kurta

seth@sethblank.com:
  email: seth@sethblank.com
  name: Seth Blank
  username: AntiFreeze

scott@kitterman.com:
  email: scott@kitterman.com
  name: Scott Kitterman
  username: kitterma

dcrocker@bbiw.net:
  email: dcrocker@bbiw.net
  name: Dave Crocker
  username: davecrocker

todd.herr@valimail.com:
  email: todd.herr@valimail.com
  name: Todd Herr
  username: toddherr

fosterd@bayviewphysicians.com:
  email: dougfoster.emailstandards@gmail.com
  name: Doug Foster
  username:

alexey.melnikov@isode.com:
  email: alexey.melnikov@isode.com
  name: Alexey Melnikov
  username:

mike@mtcc.com:
  email: mike@mtcc.com
  name: Michael Thomas
  username:

dougfoster.emailstandards@gmail.com:
  email: dougfoster.emailstandards@gmail.com
  name: Doug Foster
  username:

mail@wander.science:
  email: mail@wander.science
  name: Matthaus Wander
  username: mwander

dpa-ietf@aegee.org:
  email: dpa-ietf@aegee.org
  name: Дилян Палаузов
  username: dilyanpalauzov

alex_brotman@comcast.com:
  email: alex_brotman@comcast.com
  name: Alex Brotman
  username: abrotman

freddie@leemankuiper.nl:
  email: freddie@freddieleeman.nl
  name: Freddie Leeman
  username: freddieleeman

smj@crash.com:
  email: smj@crash.com
  name: Steve Jones
  username: smjones

tim@eudaemon.net:
  email: tim@eudaemon.net
  name: Tim Draegen
  username: tdraegen

vesely@tana.it:
  email: vesely@tana.it
  name: Alessandro Vesely
  username: alevesely

tjw.ietf@gmail.com:
  email: tjw.ietf@gmail.com
  name: Tim Wicinski
  username: moonshiner

johnl@taugh.com:
  email: johnl@taugh.com
  name: John R. Levine
  username: jrlevine

fenton@bluepopcorn.net:
  email: fenton@bluepopcorn.net
  name: Jim Fenton
  username: jimfenton

johnl@taugh.com:
  email: johnl@taugh.com
  name: John R. Levine
  username: jrlevine

Todd Herr:
  email: toddmherr@gmail.com
  name: Todd Herr
  username: toddherr

```

## Emailcore
```yaml
alexey.melnikov@isode.com:
  email: alexey.melnikov@isode.com
  name: Alexey Melnikov
  username:

julien@trigofacile.com:
  email: julien@trigofacile.com
  name: Julien ÉLIE
  username: Julien-Elie

todd.herr@valimail.com:
  email: todd.herr@valimail.com
  name: Todd Herr
  username: toddherr

resnick@episteme.net:
  email: resnick@episteme.net
  name: Pete Resnick
  username:

vesely@tana.it:
  email: vesely@tana.it
  name: Alessandro Vesely
  username: alevesely

ned.freed@mrochek.com:
  email: ned.freed@mrochek.com
  name: Ned Freed
  username: NedFreed
```

## tsvwg
```yaml
gorry@erg.abdn.ac.uk:
  email: gorry@erg.abdn.ac.uk
  name: Gorry Fairhurst
  username: gorryfair
wes@mti-systems.com:
  email: wes@mti-systems.com
  name: Wesley Eddy
  username: 
moeller0@gmx.de:
  email: moeller0@gmx.de
  name: Sebastian Moeller 
  username: 
pete@heistp.net:
  email: pete@heistp.net
  name: Pete Heist
  username: heistp
jmpolk@cisco.com:
  email: jmpolk@cisco.com
  name: James Polk
  username: 
david.black@emc.com:
  email: david.black@emc.com
  name: David Black
  username:
chromatix99@gmail.com:
  email: chromatix99@gmail.com
  name: Jonathan Morton
  username: chromi
ietf@bobbriscoe.net:
  email: ietf@bobbriscoe.net
  name: Bob Briscoe
  username: bbriscoe
jholland@akamai.com:
  email: jholland@akamai.com
  name: Jake Holland
  username: GrumpyOldTroll
g.white@cablelabs.com:
  email: g.white@cablelabs.com
  name: Greg White
  username:
lars.eggert@nokia.com:
  email: lars@eggert.org
  name: Lars Eggert
  username: larseggert
magnus.westerlund@ericsson.com:
  email: magnus.westerlund@ericsson.com
  name: Magnus Westerlund
  username: gloinul
```

**Comment by rjsparks** [comment]
david.black@emc.com -> dlb237

**Comment by ronaldtse** [comment]
Thanks @rjsparks , updated the list above for dlb237.

We're only missing these. Other than Doug Foster all the rest are still active in IETF.

```
fosterd@bayviewphysicians.com:
  email: dougfoster.emailstandards@gmail.com
  name: Doug Foster
  username:

dougfoster.emailstandards@gmail.com:
  email: dougfoster.emailstandards@gmail.com
  name: Doug Foster
  username:

alexey.melnikov@isode.com:
  email: alexey.melnikov@isode.com
  name: Alexey Melnikov
  username:

mike@mtcc.com:
  email: mike@mtcc.com
  name: Michael Thomas
  username:

wes@mti-systems.com:
  email: wes@mti-systems.com
  name: Wesley Eddy
  username: 

moeller0@gmx.de:
  email: moeller0@gmx.de
  name: Sebastian Moeller 
  username: 

g.white@cablelabs.com:
  email: g.white@cablelabs.com
  name: Greg White
  username:
```

**Comment by toddherr** [comment]
@ronaldtse I'm not sure what your definition of "active in IETF" is, but Doug Foster posted to the DMARC list as recently as January 6. Given that there's not been much activity on the list from anyone since then, I think it's premature to call him not active.

I reached out to him personally to ask him if he has a GitHub account. He doesn't, and I suggested that he create one for himself.

**Comment by ronaldtse** [comment]
@toddherr somehow I missed Doug through my Google searches! That is fantastic -- thank you @toddherr .

**Comment by HassanAkbar** [comment]
@rjsparks One important thing, we also need to invite the users to the GitHub repo before the final migration if we want the issues to be assigned to them automatically. Also, they need to accept the invite.
Otherwise, we will have to create unassigned issues.

**Comment by rjsparks** [comment]
Create unassigned issues please - I don't want to deal with the confusion that will arise as we invite people to repos before we move them to their final organization. We'll (re)-assign any that need to be assigned after.

**Comment by rjsparks** [comment]
not clear from the thread that you found it, but pete resnick ->peteresnick

**Comment by rjsparks** [comment]
Sebastian Moeller -> moeller0
Greg White -> gwhiteCL

**Comment by ronaldtse** [comment]
Thank you @rjsparks , now only 5 left to go (https://github.com/ietf-ribose/svn-github-convert/issues/59#issuecomment-1012796397)

**Comment by rjsparks** [comment]
I can't tell from the issue now, which 4 are still unresolved?

**Comment by ronaldtse** [comment]
Unresolved as of 2022-01-19:

```yaml
fosterd@bayviewphysicians.com:
  email: dougfoster.emailstandards@gmail.com
  name: Doug Foster
  username:

dougfoster.emailstandards@gmail.com:
  email: dougfoster.emailstandards@gmail.com
  name: Doug Foster
  username:

alexey.melnikov@isode.com:
  email: alexey.melnikov@isode.com
  name: Alexey Melnikov
  username:

mike@mtcc.com:
  email: mike@mtcc.com
  name: Michael Thomas
  username:

wes@mti-systems.com:
  email: wes@mti-systems.com
  name: Wesley Eddy
  username: 
```

There are 5 emails here but the first two both belong to Doug Foster, hence 4.
